Calebbii/tf 26 backend readme
sinatra-pod/moringa-library pull request #42
Opened 2023-03-08 08:07 UTC by Calebbii

2023-03-08 08:11 UTC, Calebbii commented
@otsembo

2023-03-08 21:51 UTC, otsembo requested changes
Hello @Calebbii Good job on the PR.
Kindly find some fixes I have indicated in the comments section.

Make sure to add the following as well:

- [ ] DB setup. (Explain the type of DB for production, test and development)
- [x] Add a description of how to setup their postgres database for local development

Ensure you pull all the changes from the `main` branch before making a push to the PR.

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +# THE MORINGA LIBRARY
Change the title to `Moringa Hub - API`

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +**THE MORINGA LIBRARY** is a web application that is built as a repository that features all of the best Moringa School projects done by students and technical mentors.
Provide a description that indicates that this is the backend portion of the project.

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +
Under technologies used, indicate the list of all the gems and their versions that we are using.
(List only the existing gems at this time)

NB: Ensure you also indicate their versions and what they are used for in the project.

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +
Indicate step by step how to set up the backend independently after cloning.
You can use this README as a sample: https://github.com/otsembo/my-todos-sinatra/blob/main/README.md

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +## Collaboration methodology.
Instead of `Collaboration methodology` replace with `Application`.

In this section indicate the following:

- [ ] The database models.
- [ ] The API endpoints. (Add a sample endpoint. In the sample include the route, request body and response)

You can use the above repo as a sample.

2023-03-08 21:51 UTC, otsembo commented on api/README.md
> +
Remove the authors section.

2023-03-10 07:16 UTC, Calebbii commented on api/README.md
> +## Collaboration methodology.
Changes updated.

2023-03-10 08:00 UTC, otsembo approved these changes
Everything looks good @Calebbii. Just the one minor fix I have added in the comments.
Great Job

2023-03-10 08:00 UTC, otsembo commented on api/README.md
> +8. `/` - Renders the landing page
Have only one route for now since that is what is used as a sample.
The other portions will be added by the individuals who create the specific endpoints.

I suggest the example be your number 5 in this list.

2023-03-10 08:43 UTC, otsembo reviewed
Great Job @Calebbii 

@mutuajoseph  @Albert-Byrone  Kindly make reviews on this PR.

2023-03-10 21:57 UTC, mutuajoseph approved these changes
Well documented

2023-03-11 13:37 UTC, merged