Dachoka3000/#24/ Add Project Readme
sinatra-pod/moringa-library pull request #43
Opened 2023-03-08 09:02 UTC by Dachoka3000

#24 Create README for the project

2023-03-08 21:17 UTC, Albert-Byrone requested changes
Add the Prerequisites section and a section for setting up the application with docker  e.g 
```
Prerequisites
- node v14.17.4 and above
- npm 6.14.14 and above
- React 18.2.0
```

2023-03-08 21:17 UTC, Albert-Byrone commented on README.md
> +## Requirements and Specifications
Move the versions to the technology used section(Create one if does not exist)

2023-03-08 21:24 UTC, otsembo requested changes
Hello @Dachoka3000  Good Job on the PR.
Kindly have a look at the comments below for a few fixes.

2023-03-08 21:24 UTC, otsembo commented on README.md
> +
Before adding the Authors, ensure you speak of how to set up the development environment using `.env` files.
Example:
![image](https://user-images.githubusercontent.com/38042565/223851087-cb834469-97ef-44dd-80d1-548c1c076200.png)

2023-03-08 21:24 UTC, otsembo commented on README.md
> +
Ensure your contribution guide is detailed, explaining the exact steps it takes to make the contribution.
Find below an example:
![image](https://user-images.githubusercontent.com/38042565/223851468-c48b8b36-1197-46ec-8a75-de22d6ca8979.png)

2023-03-08 21:24 UTC, otsembo commented on README.md
> -Welcome to Moringa Hub!!
You can add some shields that indicate stats about the project. Include the following:

- [ ] Issues
- [ ] Number of GitHub contributors
- [ ] GitHub repo size
- [ ] License

Use https://shields.io/ as a good reference point for all these.

2023-03-10 13:00 UTC, Dachoka3000 commented
I've made the requested changes:

- [x] Add docker setup section
- [x] Add versions in the technologies used section
- [x] Add section for setting up environment
- [x] Add a more detailed contribution guide
- [x] Add shields to indicate stats about the project. (The license shield was there already)
@Albert-Byrone  @otsembo

2023-03-10 19:54 UTC, otsembo approved these changes
Hello @Dachoka3000 Good job on the PR. make the small change.
Everything else looks okay.

2023-03-10 19:54 UTC, otsembo commented on README.md
> +* Once your code is in the remote branch, create a pull request to the `development` branch.
Change the branch to `main` instead of `development`

2023-03-12 11:56 UTC, Albert-Byrone approved these changes

2023-03-12 11:59 UTC, Albert-Byrone approved these changes

2023-03-12 11:59 UTC, otsembo approved these changes

2023-03-12 12:01 UTC, otsembo approved these changes
Looks good to me. Great job @Dachoka3000

2023-03-12 12:02 UTC, merged