Initial front-end readme
sinatra-pod/moringa-library pull request #66
Opened 2023-03-20 12:37 UTC by KelvinMuriithi

2023-03-21 01:43 UTC, otsembo approved these changes
Good Job @KelvinMuriithi

2023-03-21 19:09 UTC, Albert-Byrone requested changes
Hi @KelvinMuriithi, here are some changes to make, 

- add sections for screenshots

- remove the whitespaces around **_npm install_** and **_npm start_** command under  the setup instructions

2023-03-23 16:32 UTC, KelvinMuriithi commented
Check for the new changes made as per your review @Albert-Byrone

2023-03-23 17:37 UTC, Albert-Byrone approved these changes

2023-03-23 17:38 UTC, merged